#ifndef PATCHTOOL_CONFIG_H
#define PATCHTOOL_CONFIG_H

#define INTERNEL_PASSWORD "Q29yZXRlSw=="

#define BASE_DATABASE_FILE_NAME "baseDB"
#define PATCH_DATABASE_FILE_NAME "patchDB"
#define COMPRESSED_BASE_DATABASE_FILE_NAME "baseDB.cd"
#define COMPRESSED_PATCH_DATABASE_FILE_NAME "patchDB.cd"
#define COMPRESSED_PATCH_FILE_NAME "patch.zip"
#define CHECKSUM_FILE_NAME "checksum.txt"

#define STRING_SIZE (0x1000)

#endif //PATCHTOOL_CONFIG_H
